Removed vi mode from zshrc and update zshrc_server for home server

diff --git a/zsh/zshrc_server b/zsh/zshrc_server
--- a/zsh/zshrc_server
+++ b/zsh/zshrc_server
@@ -1,35 +1,37 @@
+# ============================== SETUP ==============================
 # Path to your oh-my-zsh configuration.
 ZSH=$HOME/.oh-my-zsh
 
 # Disables scroll lock shortcut (Ctrl+s)
 stty -ixon
 
-# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
-# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
-# Example format: plugins=(rails git textmate ruby lighthouse)
-plugins=(git command-not-found tpayne-vi-mode)
+KEYTIMEOUT=1
+
+plugins=(git command-not-found)
 
 # Set theme
-ZSH_THEME="tpayne-vm-simple"
+ZSH_THEME="tpayne-simple"
+DISABLE_AUTO_TITLE=true
 
 source $ZSH/oh-my-zsh.sh
 
-# # Good aliases
-# alias ls='ls --color=auto'
-# alias ll='ls -alhF'
-# alias la='ls -A'
-# alias l='ls -CF'
 
+# ============================== CONFIG ==============================
 # # Make some possibly destructive commands more interactive
-# alias rm='rm -i'
-# alias mv='mv -i'
-# alias cp='cp -i'
+alias rm='rm -i'
+alias mv='mv -i'
+alias cp='cp -i'
 
-# alias grep='grep -n --color=auto'
-# alias ..='cd ..'
+alias grep='grep -n --color=auto'
+alias ..='cd ..'
 
-node=`which node`
 
-if [ $node != "node not found" ]; then
-    export NODE_PATH=$node
-fi
+# ============================== FUNCTIONS ==============================
+# List processes via pgrep, then prompt to pkill - Thanks Glen
+pgk() {
+    [ -z "$*" ] && echo 'Usage: pgk <pattern>' && return 1
+    pgrep -fl $*
+    [ "$?" = "1" ] && echo 'No processes match' && return 1
+    echo 'Hit [Enter] to pkill, [Ctrl+C] to abort'
+    read && pkill -f $*
+}
